-- Create Role TABLE AND SEQUENCE

DROP TABLE IF EXISTS ROLE CASCADE;
CREATE TABLE ROLE (
    id   int8 NOT NULL,
    ROLE_NAME VARCHAR(20) NOT NULL,
    CREATED_BY VARCHAR(225),
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(225),
    LAST_MODIFIED_DATE TIMESTAMP,
    PRIMARY KEY (id)
);
DROP SEQUENCE IF EXISTS ROLE_SEQ;
CREATE SEQUENCE ROLE_SEQ
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9223372036854775807
START WITH 1
CACHE 20
OWNED BY role.id;

-- Create User TABLE AND SEQUENCE

DROP TABLE IF EXISTS SYS_USER CASCADE;
CREATE TABLE SYS_USER (
    id   int8 NOT NULL,
    NAME VARCHAR(225) NOT NULL,
    USERNAME VARCHAR(225) NOT NULL,
    PASSWORD VARCHAR(225) NOT NULL,
    EMAIL_ADDRESS VARCHAR(50) NOT NULL,
    PHONE_NUMBER VARCHAR(225),
    IS_ACTIVE Boolean,
    CREATED_BY VARCHAR(225),
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(225),
    LAST_MODIFIED_DATE TIMESTAMP,
    PRIMARY KEY (id)
);
DROP SEQUENCE IF EXISTS SYS_USER_SEQ;
CREATE SEQUENCE SYS_USER_SEQ
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9223372036854775807
START WITH 10
CACHE 20
OWNED BY sys_user.id;

-- Create User_Roles TABLE AND SEQUENCE

DROP TABLE IF EXISTS USER_ROLES;
CREATE TABLE USER_ROLES (
    USER_ID     int8 NOT NULL,
    ROLE_ID     int8 NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID)
);
DROP SEQUENCE IF EXISTS USER_ROLES_SEQ;
CREATE SEQUENCE USER_ROLES_SEQ
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9223372036854775807
START WITH 1
CACHE 20;

-- Create Contact TABLE AND SEQUENCE

DROP TABLE IF EXISTS CONTACT;
CREATE TABLE CONTACT (
    id   int8 NOT NULL,
    NAME VARCHAR(225) NOT NULL,
    CREATED_BY VARCHAR(225),
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(225),
    LAST_MODIFIED_DATE TIMESTAMP,
    PRIMARY KEY (id)
);
DROP SEQUENCE IF EXISTS CONTACT_SEQ;
CREATE SEQUENCE CONTACT_SEQ
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9223372036854775807
START WITH 10
CACHE 20
OWNED BY contact.id;