DROP TABLE IF EXISTS SYS_USER;
CREATE TABLE SYS_USER (
    id   bigint PRIMARY KEY,
    FIRST_NAME VARCHAR(225) NOT NULL,
    LAST_NAME VARCHAR(225) NOT NULL,
    EMAIL VARCHAR(225) NOT NULL
);
DROP SEQUENCE IF EXISTS SYS_USER_SEQ;
CREATE SEQUENCE SYS_USER_SEQ
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9223372036854775807
START WITH 10
CACHE 20
OWNED BY sys_user.id;